.PHONY: clean All

All:
	@echo "----------Building project:[ Menu - Debug ]----------"
	@"$(MAKE)" -f  "Menu.mk"
clean:
	@echo "----------Cleaning project:[ Menu - Debug ]----------"
	@"$(MAKE)" -f  "Menu.mk" clean
